### ISSUE TITLE
Tracking Issue: Prep for initial merge upstream

### ISSUE THREAD

**Issue by alilleybrinker** [mitre/pact-reference#62]
We're finally approaching readiness for an initial merge upstream! This is a big milestone, and represents a minimal set of functionality in `pact_matching` being exposed for FFI, and more importantly a degree of confidence that our FFI interfaces are correct and safe.

Before we do the submission, we want to kick the tires a bit and make sure 1) that the functionality / APIs are correct, and 2) that the code is well-documented and readable.

This is going to be a large PR, so we want to make sure that it's easy to understand the functionality and why it's designed the way it is. For the documentation, that means a module-by-module review to make sure we're covering safety, including what stuff needs to be freed and when.

- [x] Complete a module-by-module documentation review (tracked in #63)
- [x] ~Verify functionality through testing (tracked in #64)~ (punting on this for now)
- [x] Produce more examples of using the FFI (tracked in #65)
- [x] Audit FFI code for error handling, cloning, other practices (tracked in #66)

**Comment by alilleybrinker** [comment]
This is a tracking issue. The intent is to open individual issues for the more specific tasks we're doing, and link them back to here.

I also have it currently assigned to the February Project and Milestone but obviously we have just a few days left and I don't expect to complete it in that timeframe. It'll be reassigned when March rolls around.

**Comment by alilleybrinker** [comment]
Rather than wait, I've opted to set it to March right away.

**Comment by alilleybrinker** [comment]
The individual subtasks have now each been given their own issues.

**Comment by alilleybrinker** [comment]
This work is happening in the [`upstream_prep` branch](https://github.com/mitre/pact-reference/tree/upstream_prep). You can also see a draft description of some of the architectural choice in [`ARCHITECTURE.md`](https://github.com/mitre/pact-reference/blob/upstream_prep/rust/pact_matching_ffi/ARCHITECTURE.md).
