### ISSUE TITLE
Tracking Issue: Expose individual matching functions

### ISSUE THREAD

**Issue by alilleybrinker** [mitre/pact-reference#67]
Right now we've exposed `match_message` over FFI, but there are a number of individual matching functions which ought to be exposed over FFI as well. Unlike `match_message`, most of these rely on a parameter of type `MatchingContext` which we'll need to expose for this to work.

To start with, we'll only do the functions which rely on `MatchingContext` and existing types we can easily expose. We'll save other functions for a future round of effort.

- [ ] Expose `MatchingContext` (tracked in #68)
- [ ] Expose `match_text` (tracked in #69)
- [ ] Expose `match_path` (tracked in #70)
- [ ] Expose `match_method` (tracked in #71)
- [ ] Expose `match_status` (tracked in #72)
- [ ] Expose `match_message_contents` (tracked in #73)
- [ ] Expose `match_message_metadata` (tracked in #74)

Additionally, some of functions would require the definition of more types than we've currently done, and so are left for next steps after this initial effort:

- `match_query` (needs `Option<HashMap<String, Vec<String>>`)
- `match_body` (needs `HttpPart`)
- `match_request` (needs `Request`)
- `match_response` (needs `Response`)

Then we have longer-term or questionable functions around `Interaction`s which (I think) we currently treat as out-of-scope.

- `match_interaction_request`
- `match_interaction_response`
- `match_interaction`
